#!/bin/sh
# wchf config

while read -r l; do
    waitron wm_config ${l}
done <<EOF
border_width 2
sticky_windows true
enable_sloppy_focus true
enable_last_window_focusing true
enable_resize_hints true
groups_nr 5
EOF
