#!/bin/ksh
[[ "${-}" != *i* ]] && return 0

set -o vi
set -o vi-tabcomplete
set -o nohup bgnice trackall

unalias r w

stty -ixon

case ${KSH_VERSION:-} {
(*MIRBSD*)
    HISTFILE="${HOME}/usr/local/share/cache/mksh_history"
    ;;
(*PD*)
    HISTFILE="${HOME}/usr/local/share/cache/ksh_history"
    set -o csh-history
    ;;
}
HISTSIZE=100000

for i in prompt aliases sanedef diralias fun wrappers; {
    . ${HOME}/etc/ksh.d/${i}
}
unset i

export PS1='$(_draw_PS1)'
export PS2='... '
export LINES="${LINES}"
export COLUMNS="${COLUMNS}"
