#!/bin/ksh
[[ "${-}" != *i* ]] && return 0

set -o vi
set -o vi-tabcomplete
set -o nohup bgnice trackall

unalias r w

stty -ixon

case ${KSH_VERSION} {
(*MIRBSD*)
    HISTFILE="${HOME}/var/cache/mksh_history"
    alias !!='\\builtin fc -e -'
    ;;
(*PD*)
    HISTFILE="${HOME}/var/cache/ksh_history"
    set -o csh-history
    ;;
}
HISTSIZE=100000

_set_wn() {
    [[ ${TERM} != linux ]] &&
        print "\033]]0;ksh: ~${PWD#${HOME}}\a"
} 2> /dev/null

_rm_jnk() {
    _rm_e() {
        for i; {
            [[ -d "${i}" || -f "${i}" ]] &&
                rm -rf "${i}"
        }
    }
    _rm_e ${HOME}/.{pki,ssh}
    unset -f _rm_e
} > /dev/null

_PS1_command() {
    _set_wn; _rm_jnk
}

_draw_PS1() {
    case ${USER} {
    (root) print -n '# '               ;;
    (viz)  print -n '$ '; _PS1_command ;;
    (*)    print -n '% '               ;;
    }
}

export PS1='$(_draw_PS1)'
export PS2='... '
export LINES="${LINES}"
export COLUMNS="${COLUMNS}"

. ${HOME}/etc/aliases
