#!/bin/ksh
[[ ${-} != *i* ]] && exit 0

alias echo='builtin print'
set -o vi
set -o vi-tabcomplete
set -o nohup bgnice trackall

unalias r w

stty -ixon

case ${KSH_VERSION} {
(*MIRBSD*)
    HISTFILE="${HOME}/var/cache/mksh_history"
    alias !!='\\builtin fc -e -'
    ;;
(*PD*)
    HISTFILE="${HOME}/var/cache/ksh_history"
    set -o csh_history
    ;;
}
HISTSIZE=100000

_set_wn() {
    [[ ${TERM} != linux ]] &&
        echo -ne "\033]]0;ksh: ${PWD/~/\~}\a"
} 2> /dev/null

_rm_jnk() {
    _rm_e() {
        for i; {
            [[ -d "${i}" || -f "${i}" ]] &&
                rm -rf "${i}"
        }
    }
    _rm_e ${XDG_DESKTOP_HOME} ${HOME}/{Desktop,.dbus,.pki,.wget-hsts}
    [[ -d ${HOME}/Downloads ]] &&
        [[ -z "$(ls ${HOME}/Downloads)" ]] && rm -rf ${HOME}/Downloads
    unset -f _rm_e
} > /dev/null

_PS1_command() {
    _set_wn; _rm_jnk
}

_draw_PS1() {
    case ${USER} {
    (root) echo -n '# '               ;;
    (viz)  echo -n '$ '; _PS1_command ;;
    (*)    echo -n '% '               ;;
    }
}

export PS1='$(_draw_PS1)'
export PS2='... '

. ${HOME}/etc/aliases
