#!/bin/mksh
# vim:ft=sh
case ${-} { (*i*) ;; (*) return;; }

. ${HOME}/etc/aliases

alias echo='builtin print'
alias !!='\\builtin fc -e -'

set -o vi-tabcomplete
set -o nohup bgnice trackall

unalias r w

# dont freeze the shell when C-s is pressed
stty -ixon

# history
HISTFILE="${HOME}/var/cache/mksh_history"
HISTSIZE=100000

# vi mode
set -o vi

_set_wn() {
    [ "${TERM}" != "linux" ] && {
        local cwd="${PWD/${HOME}/\~}"
        echo -ne "\033]0;mksh: ${cwd}\a"
    }
} 2> /dev/null

# delete Desktop folder
# I HATE IT
_rm_jnk() {
    [ -d ${XDG_DESKTOP_HOME} ] && cmd rm -rf ${XDG_DESKTOP_HOME}
    [ -d ${HOME}/Desktop ] && cmd rm -rf ${HOME}/Desktop
    [ -d ${HOME}/Downloads ] &&
        [ -z "$(ls ${HOME}/Downloads)" ] && cmd rm -rf ${HOME}/Downloads
    # im not sure if this is safe but hey, I hate them
    [ -d ${HOME}/.dbus ] && cmd rm -rf ${HOME}/.dbus
    [ -d ${HOME}/.pki ] && cmd rm -rf ${HOME}/.pki
    [ -f ${HOME}/.wget-hsts ] && cmd rm -rf ${HOME}/.wget-hsts
} > /dev/null

_PS1_command() {
    _set_wn; _rm_jnk
}

# prompts
export PS1=']$(_PS1_command) '
#export PS1='\$$(_PS1_command) '
#export PS1=';$(_PS1_command) '
#export PS1='%$(_PS1_commands) '
PS2='... '
