#!/bin/sh
case ${SHELL} in
(*mksh*) . ${HOME}/etc/mkshrc;;
(*bash*) . ${HOME}/etc/bashrc;;
(*) . ${HOME}/etc/aliases;;
esac

for e in nvim vim vis vi ed; do
    case $(type -p "${e}") in
    (*"not found"*) continue;;
    (*) export EDITOR="${e}"; export VISUAL="${e}"; break;;
    esac
done

export TERMINAL="tabbed -c -r 2 st -w ''"
export MANPAGER=less

for p in \
    "${HOME}/opt/texlive/bin/x86_64-linux" \
    "${HOME}/{usr/local/,opt/cargo/,etc/xorg.d/,}bin"; do
    set -- ${p}
    for i in ${@}; do export PATH="${i}:${PATH}"; done
done

unset p

for m in \
	"${HOME}/usr/{{local/,}share/,}man" \
	"${HOME}/opt/texlive/texmf-dist/doc/man"; do
    set -- ${m}
    for i in ${@}; do export MANPATH="${MANPATH}:${i}"; done
done

unset m
unset i

export MANPATH=$MANPATH:${HOME}/opt/texlive/texmf-dist/doc/man

export XDG_CACHE_HOME="${HOME}/var/cache"
export XDG_CONFIG_HOME="${HOME}/etc/prog.d"
export XDG_DESKTOP_DIR="/non/existent"
export XDG_DOWNLOAD_DIR="${HOME}/var/downloads"
export XDG_DATA_HOME="${HOME}/var/lib"
export XAUTHORITY="${XDG_CACHE_HOME}/Xauthority"

export RUSTUP_HOME="${HOME}/opt/rustup"
export CARGO_HOME="${HOME}/opt/cargo"

export MAIL="${HOME}/var/mail/inbox"

export CPATH="${HOME}/usr/local/include:$HOME/usr/include"
export LD_LIBRARY_PATH="${HOME}/usr/local/lib"

export PYTHONUSERBASE="${HOME}/usr/lib/python3"
export PYTHONPATH="${HOME}/usr/lib/python3"
export PYTHONSTARTUP="${HOME}/etc/pythonrc"

export NVIM_LOG_FILE="${HOME}/var/logs/nvim.log"
export LESSHISTFILE="${HOME}/var/cache/lesshst"

export WEECHAT_HOME="${HOME}/etc/weechat"

export GNUPGHOME="${HOME}/etc/gnupg"

[ -n "$(command -v clang)" ] && export CC=clang

case $(tty) in
(*1*) sx;;
esac
