#!/bin/sh
export TERMINAL='tabbed -r 2 st -w ""'
export MANPAGER=less

for p in \
    ${HOME}/opt/texlive/bin/x86_64-linux \
    ${HOME}/{usr/local/,opt/{cargo/,racket/7.3/},}bin; do
        PATH="${p}:${PATH}"
done

case ${SHELL} in
(*ksh*)
    . ${HOME}/etc/kshrc
    export ENV=${HOME}/etc/kshrc
    ;;
esac

export EDITOR=vi
export VISUAL=vi

export MANPATH="/usr/share/man:${HOME}/usr/local/share/man"
export INPUTRC="${HOME}/etc/inputrc"

export XDG_CACHE_HOME="${HOME}/var/cache"
export XDG_CONFIG_HOME="${HOME}/etc/prog.d"
export XDG_DESKTOP_DIR='/non/existent'
export XDG_DOWNLOAD_DIR="${HOME}/var/downloads"
export XDG_DATA_HOME="${HOME}/var/lib"

export RUSTUP_HOME="${HOME}/opt/rustup"
export CARGO_HOME="${HOME}/opt/cargo"

export MAIL="${HOME}/var/mail/inbox"

export CPATH="${HOME}/usr/local/include:$HOME/usr/include"
export LD_LIBRARY_PATH="${HOME}/usr/local/lib"

export PYTHONUSERBASE="${HOME}/usr/local"
export PYTHONPATH="${HOME}/usr/local"
export PYTHONSTARTUP="${HOME}/etc/prog.d/pythonrc"

export LESSHISTFILE="${HOME}/var/cache/lesshst"

export GNUPGHOME="${HOME}/etc/gnupg"

# fix font rendering THANK YOU ZOE. BIG HUG
export FREETYPE_PROPERTIES='truetype:interpreter-version=38'
