#!/bin/sh
# $HOME/etc/profile
# source our shellrc
case $SHELL in
    *ksh*) source $HOME/etc/kshrc;;
    *bash*) source $HOME/etc/bashrc;;
esac

# exporting variables
export EDITOR=nvim
export VISUAL=nvim
export PATH=$PATH:$HOME/bin/:$HOME/.local/bin:$HOME/usr/local
export PATH=$PATH:$HOME/usr/local/bin
export MANPATH=$MANPATH:$HOME/usr/local/man:$HOME/usr/man
export TERMINAL="tabbed -c -r 2 st -w ''"
export MANPAGER="nvim -c 'set ft=man nonu ts=2'"

# XDG env vars
export XDG_CACHE_HOME="$HOME/var/cache"
export XDG_CONFIG_HOME="$HOME/etc"
export XDG_DESKTOP_DIR="$HOME/tmp/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/var/downloads"
