set rtp+=~/etc/vim/bundle/Vundle.vim
set rtp+=~/etc/vim
call vundle#begin('~/etc/vim/plugins')

Plugin 'VundleVim/Vundle.vim'

Plugin 'jiangmiao/auto-pairs'
Plugin 'davidhalter/jedi-vim'
Plugin 'rust-lang/rust.vim'
"Plugin 'vim-syntastic/syntastic'
Plugin 'ervandew/supertab'
Plugin 'vitalk/vim-shebang'
Plugin 'dylanaraps/fff.vim'
Plugin 'autozimu/LanguageClient-neovim'
Plugin 'Shougo/deoplete.nvim'

Plugin 'Yggdroot/indentLine'
Plugin 'junegunn/goyo.vim'

call vundle#end()
filetype plugin indent on

if !has('nvim')
  set ttymouse=xterm2
endif

syntax on
filetype plugin on

set number
set relativenumber
set ruler
"set cursorline " its kind of slow

set tabstop=4
set shiftwidth=4
set smarttab
set et

set encoding=utf-8

set laststatus=0

set ignorecase
set smartcase

tnoremap <C-x><Esc> <C-\><C-N>

set t_Co=256

set nocompatible

colorscheme roman

set clipboard=unnamedplus

set title titlestring=nvim:\ %F titlelen=80

autocmd BufWritePre * %s/\s\+$//e

autocmd TermOpen * setlocal nonumber norelativenumber

set splitright

set columns=80

set guicursor=

set noswapfile
set autoread

let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
let g:webdevicons_enable_airline_statusline = 1
let g:webdevicons_enable_ctrlp = 1

let g:jedi#completions_command = "<C-x><Tab>"

let g:rustfmt_autosave = 1 "enable rust format

let g:ale_completion_enabled = 1
hi ALEErrorSign ctermbg=NONE ctermfg=1 cterm=NONE
hi ALEWarningSign ctermbg=NONE ctermfg=11 cterm=NONE
hi ALEError ctermbg=NONE ctermfg=1 cterm=NONE
hi ALEWarning ctermbg=NONE ctermfg=11 cterm=NONE
let g:ale_sign_error = ">"
let g:ale_sign_warning = "-"

let g:indentLine_setColors = 1
let g:indentLine_char = '|'
let g:indentLine_first_char = "|"
let g:indentLine_bgcolor_term = 0
let g:indentLine_showFirstLevelIndentLevel = 1
let g:indentLine_fileTypeExclude = ['man', 'help', 'terminal', 'json', 'mail']
let g:indentLine_bufTypeExclude = ['man', 'help', 'terminal', 'json', 'mail']
let g:indentLine_bufNameExclude = ['NERD_tree.*', 'term://*', "man:*"]

let g:deoplete#enable_at_startup = 1
let g:LanguageClient_serverCommands = {
            \ 'rust': ['rustup', 'run', 'nightly', 'rls']
            \}

filetype indent on

AddShebangPattern! sh ^#!.*/bin/dash\>
