" vim config

" set the runtime path to include Vundle and initialize
set rtp+=~/etc/vim/bundle/Vundle.vim
set rtp+=~/etc/vim
call vundle#begin("~/etc/vim/plugins")

Plugin 'VundleVim/Vundle.vim'

" Own plugins
" General
Plugin 'jiangmiao/auto-pairs'
Plugin 'scrooloose/nerdtree'
Plugin 'davidhalter/jedi-vim' "because python
Plugin 'rust-lang/rust.vim' "rust yummy
Plugin 'justmao945/vim-clang' "C is good
Plugin 'jistr/vim-nerdtree-tabs' " I like me some fancy stuff
Plugin 'vim-syntastic/syntastic' " it saves me some time
Plugin 'ervandew/supertab' " using tab for completion is better
Plugin 'vitalk/vim-shebang'
Plugin 'w0rp/ale' "linter

" Beautify
Plugin 'ryanoasis/vim-devicons'
Plugin 'ryanoasis/vim-webdevicons'
Plugin 'morhetz/gruvbox'
Plugin 'vim-scripts/twilight256.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'chriskempson/base16-vim'
Plugin 'junegunn/goyo.vim'
" no vimairline for ya

call vundle#end()
filetype plugin indent on

" nvim is better. change my mind
if !has('nvim')
  set ttymouse=xterm2
endif

" for moar colors
syntax on
filetype plugin on

" because I can't live without enabling it
" hybridnumber > number > relativenumber
set number
set relativenumber
set ruler
"set cursorline " its kind of slow

" indentation
set tabstop=4
set shiftwidth=4
set et

" encoding for making lives easier
set encoding=utf-8

" hide statusbar. I don't like it. change my mind
set laststatus=0

" better search imo
set ignorecase
set smartcase

" maps C-x Esc to go to normal mode while in :term
tnoremap <C-x><Esc> <C-\><C-N>

" set 256 colors
set t_Co=256

" keybindings
nmap <F6> :NERDTreeToggle<CR>
nnoremap <F8> :SyntasticCheck<CR>

" be improved
set nocompatible

" colorscheme
colorscheme viking

" yank to clipboard
set clipboard=unnamedplus

" set window's title
" title is set to the full path of the file
set title titlestring=nvim:\ %F titlelen=80

" remove trailing whitespaces before writing
autocmd BufWritePre * %s/\s\+$//e

" disable line numbers in terminal
autocmd TermOpen * setlocal nonumber norelativenumber

" split stuff
set splitright

" set columns limit to 80
set columns=80
set tw=80

" Plugin's config

"devicons
let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
let g:webdevicons_enable_airline_statusline = 1
let g:webdevicons_enable_ctrlp = 1

"syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
autocmd VimEnter * SyntasticToggleMode

"jedi-vim
let g:jedi#completions_command = "<C-x><Tab>"

"rust-lang
let g:rustfmt_autosave = 1 "enable rust format

"linter
"completition
let g:ale_completion_enabled = 1
hi ALEErrorSign ctermbg=NONE ctermfg=1 cterm=NONE
hi ALEWarningSign ctermbg=NONE ctermfg=11 cterm=NONE
hi ALEError ctermbg=NONE ctermfg=1 cterm=NONE
hi ALEWarning ctermbg=NONE ctermfg=11 cterm=NONE
let g:ale_sign_error = ">"
let g:ale_sign_warning = "-"

"indentguides config
let g:indentLine_setColors = 1
let g:indentLine_char = '|'
let g:indentLine_first_char = "|"
let g:indentLine_bgcolor_term = 0
let g:indentLine_showFirstLevelIndentLevel = 1
let g:indentLine_fileTypeExclude = ['man', 'help', 'terminal', 'json']
let g:indentLine_bufTypeExclude = ['man', 'help', 'terminal', 'json']
let g:indentLine_bufNameExclude = ['NERD_tree.*', 'term://*', "man:*"]

filetype indent on

AddShebangPattern! sh ^#!.*/bin/dash\>
