#!/bin/sh
cd $HOME
xmodmap $HOME/etc/xmodmap
xset +fp $HOME/usr/fonts
sxhkd -c $HOME/etc/sxhkdrc -r $HOME/var/log/sxhkd.log -s $HOME/var/log/sxhkd.log &
#swall set &
hsetroot -solid \#dde0e2

[ $(xrandr --nograb --current | grep -o \* | wc -l) = 2 ] && mon on

exec dwm 2> $HOME/var/log/dwm.log
