#!/bin/ksh

alias a='alias'
a cmd='command'

has python3 && a {py,python}='python3'
has racket  && a rkt='racket'
has perl    && a pl='perl'
has mupdf   && a mpf='mupdf'
has zathura && a mpf='zathura'
has noice   && a {fm,mf}='noice'
has mk      || a mk='make'
has doas    && a doas='doas '

a {mkci,mkic}='make clean install'
a mki='make install'
a mka='make all'
a mku='make uninstall'
a mkc='make clean'
a rsc='resource'
a aliases='alias'
a {quit,:q,:q!}='exit'

a {cd..,c..,c.}='cd ..'
a {cl,cle,clea}='clear'
