#!/bin/ksh

while read -r al; do
    set -- ${al}
    a g${1}="cd ${2}"
    a -d ${1}=${2}
done << EOF
H ${HOME}
B ${HOME}/bin
S ${HOME}/usr/src
R ${HOME}/usr/repos
T ${HOME}/tmp
W ${HOME}/usr/share/img/walls
E ${HOME}/etc
D ${HOME}/usr/doc
C ${XDG_CACHE_HOME}
P ${HOME}/usr/ports
M ${HOME}/usr/share/mus
s ${HOME}/usr/share
p /usr/ports
m /mnt
EOF
