#!/bin/ksh

while read -r al; do
    a g${al% *}="cd ${al#* }"
    a -d ${al% *}="${al#* }"
done <<EOF
H ${HOME}
B ${HOME}/bin
S ${HOME}/usr/src
R ${HOME}/usr/repos
T ${HOME}/tmp
W ${HOME}/usr/share/img/walls
E ${HOME}/etc
D ${HOME}/usr/doc
C ${XDG_CACHE_HOME}
P ${HOME}/usr/ports
M ${HOME}/usr/share/mus
s ${HOME}/usr/share
e ${HOME}/usr/env
p /usr/ports
m /mnt
EOF

a c..='cd ..'
a ..='cd ..'
