#!/bin/ksh

_set_wn() {
    case ${TERM} {
    (linux|dumb)
        ;;
    (*)
        printf '\033]]0;ksh: %s\a' ${PWD/${HOME}/\~}
        ;;
    }
} 2> /dev/null

_rm_jnk() {
    _rm_e() {
        for i; {
            [[ -d "${i}" || -f "${i}" ]] &&
                rm -rf "${i}"
        }
    }
    _rm_e ${HOME}/.pki
    unset -f _rm_e
} > /dev/null

_PS1_command() {
    _set_wn; _rm_jnk
}

_draw_PS1() {
    case `whoami` {
    (root) print -n '# '               ;;
    (viz)  print -n '$ '; _PS1_command ;;
    (*)    print -n '% '               ;;
    }
}
