#!/bin/ksh

while read -r al; do
    a ${al%% *}="${al}"
done <<EOF
df -h
du -h
mv -iv
rm -v
cp -rv
ln -sf
free -h
fc-cache --verbose
grep -i
su -
ls -AF
mpv --no-audio-display
EOF

a mkf='touch'
a mkd='mkdir -pv'
a sl='ls'
a rmf='rm -rf'
a SU='doas ksh'

a reboot='doas reboot'
a poweroff='doas poweroff'
a shutdown='doas shutdown'

a datenow='date +"%a %d %b %Y %H:%M"'
