#!/bin/sh
# wchf config

# For border_width, color_{un,}focused, settings apply in the range
# N, N-1, N-2, N-3, ...., 1

while read -r l; do
    waitron wm_config ${l}
done <<EOF
number_borders 3
border_width 5 1 5
color_focused   ffffea 6ecbdc ffffea
color_unfocused ffffea cccccc ffffea
decor_size 0
enable_borders true
sticky_windows true
enable_sloppy_focus true
enable_last_window_focusing true
enable_resize_hints true
groups_nr 5
pointer_modifier super
EOF

waitron refresh_borders
