# -*- mode: sh; -*-

[[ "${-}" != *i* ]] && return 0

set -o nohup bgnice trackall utf8-mode

stty -ixon

case ${KSH_VERSION} {
*MIRBSD*)
	HISTFILE="${HOME}/.cache/mksh_history"
	HISTSIZE=65535
	;;
*PD*)
	HISTFILE="${HOME}/.cache/ksh_history"
	HISTSIZE=100000
	set -o csh-history
	;;
}

for i in prompt aliases sanedef diralias fun wrappers; {
	. ${HOME}/lib/ksh/${i}
}
unset i

export LINES="${LINES}"
export COLUMNS="${COLUMNS}"
