[[ "${-}" != *i* ]] && return 0

set -o vi vi-tabcomplete nohup bgnice trackall

stty -ixon

case ${KSH_VERSION} {
*MIRBSD*)
    HISTFILE="${HOME}/.cache/mksh_history"
	HISTSIZE=65535
    ;;
*PD*)
    HISTFILE="${HOME}/.cache/ksh_history"
    set -o csh-history
    ;;
}
HISTSIZE=100000

for i in prompt aliases sanedef diralias wrappers fun; {
    . ${HOME}/lib/ksh/${i}
}
unset i

export PS1='$(_draw_PS1)'
export PS2='... '
export LINES="${LINES}"
export COLUMNS="${COLUMNS}"
