#!/bin/sh
# MANAGED BY NIX NOW

. ${HOME}/.nix-profile/etc/profile.d/hm-session-vars.sh

pass get irc/Freenode >/dev/null

case ${SHELL} in
*/bin/mksh)
    export ENV=${HOME}/lib/kshrc
    . ${HOME}/lib/kshrc
    ;;
esac
