#!/bin/dash
autils_path="$HOME/usr/src/pacwoman/autils"

usage() {
    echo "usage\n---------------\n"
    echo "[-i] install package(s)"
    echo "[-u] update aur package(s)"
}

case "$1" in
    -i) shift; ${autils_path}/install $@;;
    -u) ${autils_path}/update;;
    *) usage;;
esac
