#!/usr/bin/env mksh

_set_wn() {
	case ${TERM} {
	linux|dumb)
	    ;;
	*)
		local sh=ksh
		[[ -n "${IN_NIX_SHELL}" ]] && sh='*ksh'
	    printf '\033]]0;%s: %s\a' "${sh}" ~${PWD#${HOME}}
	    ;;
	}
} 2>/dev/null

_rm_jnk() {
	_rm_e() { for i; {
	        [[ -d "${i}" || -f "${i}" ]] &&
	            rm -rf "${i}"
	    }
	}
	_rm_e ${HOME}/.{dbus,pki,ssh}
	unset -f _rm_e
} >/dev/null

_PS1_command() {
	_set_wn; _rm_jnk
}

_draw_PS1() {
	[[ -n "${IN_NIX_SHELL}" ]] && print -n '*'
	case `whoami` {
	root) print -n '# '               ;;
	viz)  print -n '$ '; _PS1_command ;;
	*)    print -n '% '               ;;
	}
}
