#!/bin/sh

cd ${HOME}
export WM=wchf
export PATH=${HOME}/bin/x:${PATH}

export XFONT='monospace:pixelsize=12:hinting=true:rgba=none'
export TERMINAL='tabbed -r 2 st -w ""'

remkd /tmp/info /tmp/info/vol

sxhkd -c ${HOME}/lib/sxhkd/sxhkdrc &
. ${XDG_CACHE_HOME}/wall &
pmenu &

exec ${WM}
